name: C/C++ CI

on:
  push:
    branches:
      - develop

jobs:
  build-macos:
    name: build for macos
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: run cmake
      run: mkdir build && cd build && cmake ..
